
    "core/lib/state",
    "core/lib/storage",
    "core/lib/types",
    "core/lib/protobuf_config",
    "core/lib/utils",
    "core/lib/vlog",
    "core/lib/multivm",
    "core/lib/vm_utils",
    "core/lib/web3_decl",
    "core/lib/snapshots_applier",

    # Test infrastructure
    "core/tests/test_account",
    "core/tests/loadnext",
    "core/tests/vm-benchmark",
    "core/tests/vm-benchmark/harness",

    # SDK section
    "sdk/zksync-rs",
]
resolver = "2"

exclude = []

# for `perf` profiling
[profile.perf]
inherits = "release"
debug = true
